### ISSUE TITLE
Dropbox 連結失效

### ISSUE THREAD

**Issue by samx81** [Taiwanese-Corpus/Pakhelke-1916_Taiwanese-Bible#1]
你好，

我想用這個語料訓練看看 ASR，然而如標題所述，連結無法存取，
請問是否方便更新連結，或是能夠提供程式碼讓我自行處理分段。

謝謝

**Comment by sih4sing5hong5** [comment]
多謝回報，https://github.com/Taiwanese-Corpus/Pakhelke-1916_Taiwanese-Bible/commit/dc327bc0d16b8abb65844849aae614c095988fc7 改好勢。

若是ASR，阮嘛有錄 [SuiSiann](https://duckduckgo.com/?t=lm&q=suisiann-data) ，請參考[授權範圍](https://github.com/i3thuan5/SuiSiann-KauTui/issues/371)。

**Comment by samx81** [comment]
下載成功了，感謝！

**Comment by sih4sing5hong5** [comment]
多謝回報，按呢我結案～
